name: Kwiki-Icons-Gnome
version: 0.14
abstract: Kwiki Gnome Icons Plugin
author: Ian Langworth <langworth.com>
license: gpl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
  Kwiki::Icons: 0
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.35
