name: Kwiki-Icons-Gnome
version: 0.10
abstract: Kwiki Gnome Icons Plugin
author: Brian Ingerson <ingy@cpan.org>
license: gpl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.30
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.33
